### ISSUE TITLE
[Bug] NavPills height can not auto change

### ISSUE THREAD

**Issue by clwater** [creativetimofficial/ct-material-kit-pro-react#68] opened 2020-10-24 19:22 UTC
### Version
v1.9
### Reproduction link
https://jsfiddle.net/
### Operating System
Mac
### Device
PC
### Browser & Version
Version 86.0.4240.111 (Official Build) (x86_64)
### Steps to reproduce
use NavPills
add 2 element in tabs attribute
one of this have many info, and the other have less
### What is expected?
when i change the less tab, The NavPills height need auto fix.
### What is actually happening?
when i change the less tab,  the NavPills height is also with original tab height,

---

**Comment by einazare** [comment] 2020-10-26 07:16
Hello there, @clwater ,

This is not a bug, it's actually default behavior, and we will not change this.
You can add default height for the NavbPilss like this:
1. Go inside `src/assets/jss/material-kit-pro-react/components/navPillsStyle.js`
2. Replace
```
  contentWrapper: {
    marginTop: "20px",
    "& .react-swipeable-view-container > div > div": {
      paddingLeft: "15px",
      paddingRight: "15px"
    }
  },
```
3. With
```
  contentWrapper: {
    height: "700px",
    marginTop: "20px",
    "& .react-swipeable-view-container > div > div": {
      paddingLeft: "15px",
      paddingRight: "15px"
    }
  },
```
4. Replace the `700px` from the previous step, with the desired height.

Since this is not actually an issue, but more like help wanted, and I've added the solution here, I will close this issue.

Best,
Manu

**Closed as completed by einazare** 2020-10-26 07:16 UTC

**Comment by clwater** [comment] 2020-10-26 07:56
Sorry, This do not workd
In my NavPills, one tab heght is more than 700 px(like 5000), the other is less than 700, 
when i change the style as you provide, 
In my view, the  NavPills height if fixed, the less than 700 tab can correct display, but the more than 700(5000) tab can ont display all info.
What should i do?
or How can make NavPills height auto with choose tab?

**Comment by clwater** [comment] 2020-10-26 07:57
> Hello there, @clwater ,
> 
> This is not a bug, it's actually default behavior, and we will not change this.
> You can add default height for the NavbPilss like this:
> 
> 1. Go inside `src/assets/jss/material-kit-pro-react/components/navPillsStyle.js`
> 2. Replace
> 
> ```
>   contentWrapper: {
>     marginTop: "20px",
>     "& .react-swipeable-view-container > div > div": {
>       paddingLeft: "15px",
>       paddingRight: "15px"
>     }
>   },
> ```
> 
> 1. With
> 
> ```
>   contentWrapper: {
>     height: "700px",
>     marginTop: "20px",
>     "& .react-swipeable-view-container > div > div": {
>       paddingLeft: "15px",
>       paddingRight: "15px"
>     }
>   },
> ```
> 
> 1. Replace the `700px` from the previous step, with the desired height.
> 
> Since this is not actually an issue, but more like help wanted, and I've added the solution here, I will close this issue.
> 
> Best,
> Manu

Sorry, This do not workd
In my NavPills, one tab heght is more than 700 px(like 5000), the other is less than 700,
when i change the style as you provide,
In my view, the NavPills height if fixed, the less than 700 tab can correct display, but the more than 700(5000) tab can ont display all info.
What should i do?
or How can make NavPills height auto with choose tab?

**Comment by einazare** [comment] 2020-10-26 14:20
Hello again, @clwater ,

> What should i do?

You can add `5000px` instead of the `700px`.
> or How can make NavPills height auto with choose tab?

The NavPills height already come with auto height, so you should just revert the above changes.

Best,
Manu

**Comment by clwater** [comment] 2020-10-26 15:24
> Hello again, @clwater ,
> 
> > What should i do?
> 
> You can add `5000px` instead of the `700px`.
> 
> > or How can make NavPills height auto with choose tab?
> 
> The NavPills height already come with auto height, so you should just revert the above changes.
> 
> Best,
> Manu

Yes , the NavPills height should auto fix,  but when i choose differ tab, the NavPills always is the tallest heigh(like 5000),
so, this sitation is right?

**Comment by einazare** [comment] 2020-10-26 15:42
Hello again, @clwater ,

> Yes , the NavPills height should auto fix, but when i choose differ tab, the NavPills always is the tallest heigh(like 5000),
so, this sitation is right?

This cannot be achieved.

Best,
Manu
